baseURL = "https://mikey.codes/"
languageCode = "en-gb"
title = "Mikey Codes"
theme = "hugo-cactus-theme"
disqusShortname = "mikey-codes"

[params]
	name = "Mikey"
	description = "Manchester based Software Engineer "
	bio = "Software Engineer, Runner and Self-help addict"
	# Enter optionally your twitter account
	twitter = "mikeycodes"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Software Engineer & Self-help addict"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

# Add additional social link entries underneath
[social]
    circletwitterbird = "https://www.twitter.com/mikeycodes"
    circlegithubalt = "https://www.github.com/mikeyscode"
    circlelinkedin = "https://www.linkedin.com/in/michael-leah-0b9281a7/"
